languageCode: "en-US"
title: "Open Science with ASE"
theme: "simplecss"
baseURL: https://ase-workshop-2023.github.io

params:
  description: "Open Science with the Atomic Simulation: April 24-28 2023"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Venue & Arrival
      url: "timetable/index.html"
      weight: 2
